/*
  Warnings:

  - You are about to drop the column `autoGenerated` on the `artists` table. All the data in the column will be lost.
  - You are about to drop the column `userId` on the `artists` table. All the data in the column will be lost.
  - You are about to drop the column `isAnonymous` on the `reviews` table. All the data in the column will be lost.
  - You are about to drop the column `isReported` on the `reviews` table. All the data in the column will be lost.
  - You are about to drop the `healed_photo_prompts` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `notification_preferences` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `notifications` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `portfolio_comments` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `portfolio_images` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `promotions` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `review_comments` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `review_photos` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `review_reports` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `social_accounts` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `tattoo_categories` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `users` table. If the table is not empty, all the data it contains will be lost.
  - A unique constraint covering the columns `[email]` on the table `artists` will be added. If there are existing duplicate values, this will fail.
  - A unique constraint covering the columns `[username]` on the table `artists` will be added. If there are existing duplicate values, this will fail.
  - Added the required column `email` to the `artists` table without a default value. This is not possible if the table is not empty.
  - Added the required column `password` to the `artists` table without a default value. This is not possible if the table is not empty.
  - Added the required column `username` to the `artists` table without a default value. This is not possible if the table is not empty.

*/
-- DropForeignKey
ALTER TABLE "public"."artists" DROP CONSTRAINT "artists_userId_fkey";

-- DropForeignKey
ALTER TABLE "public"."healed_photo_prompts" DROP CONSTRAINT "healed_photo_prompts_reviewId_fkey";

-- DropForeignKey
ALTER TABLE "public"."portfolio_comments" DROP CONSTRAINT "portfolio_comments_parent_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."portfolio_comments" DROP CONSTRAINT "portfolio_comments_portfolioImageId_fkey";

-- DropForeignKey
ALTER TABLE "public"."portfolio_comments" DROP CONSTRAINT "portfolio_comments_userId_fkey";

-- DropForeignKey
ALTER TABLE "public"."portfolio_images" DROP CONSTRAINT "portfolio_images_artistId_fkey";

-- DropForeignKey
ALTER TABLE "public"."promotions" DROP CONSTRAINT "promotions_artistId_fkey";

-- DropForeignKey
ALTER TABLE "public"."review_comments" DROP CONSTRAINT "review_comments_parent_id_fkey";

-- DropForeignKey
ALTER TABLE "public"."review_comments" DROP CONSTRAINT "review_comments_reviewId_fkey";

-- DropForeignKey
ALTER TABLE "public"."review_comments" DROP CONSTRAINT "review_comments_userId_fkey";

-- DropForeignKey
ALTER TABLE "public"."review_photos" DROP CONSTRAINT "review_photos_reviewId_fkey";

-- DropForeignKey
ALTER TABLE "public"."review_reports" DROP CONSTRAINT "review_reports_reporterId_fkey";

-- DropForeignKey
ALTER TABLE "public"."review_reports" DROP CONSTRAINT "review_reports_reviewId_fkey";

-- DropForeignKey
ALTER TABLE "public"."reviews" DROP CONSTRAINT "reviews_clientId_fkey";

-- DropForeignKey
ALTER TABLE "public"."social_accounts" DROP CONSTRAINT "social_accounts_userId_fkey";

-- DropIndex
DROP INDEX "public"."artists_userId_key";

-- AlterTable
ALTER TABLE "public"."artists" DROP COLUMN "autoGenerated",
DROP COLUMN "userId",
ADD COLUMN     "email" TEXT NOT NULL,
ADD COLUMN     "location" TEXT,
ADD COLUMN     "name" TEXT,
ADD COLUMN     "password" TEXT NOT NULL,
ADD COLUMN     "profilePhoto" TEXT,
ADD COLUMN     "socialLinks" JSONB,
ADD COLUMN     "socialLogin" JSONB,
ADD COLUMN     "socialVerified" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "username" TEXT NOT NULL;

-- AlterTable
ALTER TABLE "public"."reviews" DROP COLUMN "isAnonymous",
DROP COLUMN "isReported",
ADD COLUMN     "photoUrls" TEXT[];

-- DropTable
DROP TABLE "public"."healed_photo_prompts";

-- DropTable
DROP TABLE "public"."notification_preferences";

-- DropTable
DROP TABLE "public"."notifications";

-- DropTable
DROP TABLE "public"."portfolio_comments";

-- DropTable
DROP TABLE "public"."portfolio_images";

-- DropTable
DROP TABLE "public"."promotions";

-- DropTable
DROP TABLE "public"."review_comments";

-- DropTable
DROP TABLE "public"."review_photos";

-- DropTable
DROP TABLE "public"."review_reports";

-- DropTable
DROP TABLE "public"."social_accounts";

-- DropTable
DROP TABLE "public"."tattoo_categories";

-- DropTable
DROP TABLE "public"."users";

-- DropEnum
DROP TYPE "public"."CategoryType";

-- DropEnum
DROP TYPE "public"."NotificationType";

-- DropEnum
DROP TYPE "public"."PaymentStatus";

-- DropEnum
DROP TYPE "public"."PhotoType";

-- DropEnum
DROP TYPE "public"."PromotionType";

-- DropEnum
DROP TYPE "public"."ReportReason";

-- DropEnum
DROP TYPE "public"."ReportStatus";

-- DropEnum
DROP TYPE "public"."UserRole";

-- CreateTable
CREATE TABLE "public"."admins" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "name" TEXT,
    "profilePhoto" TEXT,
    "isSuper" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "admins_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."clients" (
    "id" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "name" TEXT,
    "profilePhoto" TEXT,
    "location" TEXT,
    "socialLinks" JSONB,
    "socialLogin" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "clients_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."PortfolioImage" (
    "id" TEXT NOT NULL,
    "artistId" TEXT NOT NULL,
    "imageUrls" TEXT[],
    "caption" TEXT,
    "isPublic" BOOLEAN NOT NULL DEFAULT true,
    "uploadedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PortfolioImage_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."ReviewComment" (
    "id" TEXT NOT NULL,
    "clientId" TEXT,
    "reviewId" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ReviewComment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."PortfolioComment" (
    "id" TEXT NOT NULL,
    "clientId" TEXT NOT NULL,
    "portfolioImageId" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PortfolioComment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."ReviewReport" (
    "id" TEXT NOT NULL,
    "reviewId" TEXT NOT NULL,
    "reporterId" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ReviewReport_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."Promotion" (
    "id" TEXT NOT NULL,
    "artistId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "price" DOUBLE PRECISION,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Promotion_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "admins_email_key" ON "public"."admins"("email");

-- CreateIndex
CREATE UNIQUE INDEX "clients_username_key" ON "public"."clients"("username");

-- CreateIndex
CREATE UNIQUE INDEX "clients_email_key" ON "public"."clients"("email");

-- CreateIndex
CREATE UNIQUE INDEX "artists_email_key" ON "public"."artists"("email");

-- CreateIndex
CREATE UNIQUE INDEX "artists_username_key" ON "public"."artists"("username");

-- AddForeignKey
ALTER TABLE "public"."reviews" ADD CONSTRAINT "reviews_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "public"."clients"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."PortfolioImage" ADD CONSTRAINT "PortfolioImage_artistId_fkey" FOREIGN KEY ("artistId") REFERENCES "public"."artists"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ReviewComment" ADD CONSTRAINT "ReviewComment_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "public"."clients"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ReviewComment" ADD CONSTRAINT "ReviewComment_reviewId_fkey" FOREIGN KEY ("reviewId") REFERENCES "public"."reviews"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."PortfolioComment" ADD CONSTRAINT "PortfolioComment_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "public"."clients"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."PortfolioComment" ADD CONSTRAINT "PortfolioComment_portfolioImageId_fkey" FOREIGN KEY ("portfolioImageId") REFERENCES "public"."PortfolioImage"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ReviewReport" ADD CONSTRAINT "ReviewReport_reviewId_fkey" FOREIGN KEY ("reviewId") REFERENCES "public"."reviews"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ReviewReport" ADD CONSTRAINT "ReviewReport_reporterId_fkey" FOREIGN KEY ("reporterId") REFERENCES "public"."clients"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Promotion" ADD CONSTRAINT "Promotion_artistId_fkey" FOREIGN KEY ("artistId") REFERENCES "public"."artists"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."admin_logs" ADD CONSTRAINT "admin_logs_adminId_fkey" FOREIGN KEY ("adminId") REFERENCES "public"."admins"("id") ON DELETE CASCADE ON UPDATE CASCADE;
